# Generated by Django 4.2 on 2023-04-07 18:33

from django.db import migrations, models
import django.db.models.deletion
import doors.models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='door',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='door',
            name='title',
        ),
        migrations.AddField(
            model_name='door',
            name='glazing_img',
            field=models.ImageField(blank=True, upload_to=doors.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='door',
            name='height',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='door',
            name='thickness',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='door',
            name='width',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='door',
            name='color_patina',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='door',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='image',
            field=models.ImageField(blank=True, upload_to=doors.models.image_upload_path),
        ),
        migrations.CreateModel(
            name='DoorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='door',
            name='doortype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doors.doortype'),
            preserve_default=False,
        ),
    ]
