# Generated by Django 4.2 on 2023-04-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_remove_door_collection_remove_door_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='glazing',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
