# Generated by Django 4.2 on 2023-04-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0003_alter_door_glazing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='description',
        ),
        migrations.AddField(
            model_name='door',
            name='mouldings',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doortype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
