# Generated by Django 4.2 on 2023-04-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0004_remove_door_description_door_mouldings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='glazing_img',
        ),
    ]
