# Generated by Django 4.2 on 2023-04-15 21:39

from django.db import migrations, models
import doors.models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0007_news_extra_img1_news_extra_img2_news_extra_img3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('emai', models.EmailField(max_length=254)),
                ('text_message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='extra_img1',
            field=models.ImageField(blank=True, upload_to=doors.models.news_image_upload),
        ),
        migrations.AlterField(
            model_name='news',
            name='extra_img2',
            field=models.ImageField(blank=True, upload_to=doors.models.news_image_upload),
        ),
        migrations.AlterField(
            model_name='news',
            name='extra_img3',
            field=models.ImageField(blank=True, upload_to=doors.models.news_image_upload),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=doors.models.news_image_upload),
        ),
    ]
